spring:
  application:
    name: catalog-service

  flyway:
    url: ${DB_JDBC_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration

  main:
    web-application-type: reactive

  jackson:
    serialization:
      indent-output: true

postgresql:
  host: ${DB_R2DBC_URL}
  port: 5432
  database: postgres
  schema: public
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  ssl: allow

server:
  port: 8080

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    org.springframework.security: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always