name: terraform-deploy-all

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      ###################################################
      # MODULE 1: terraform-preinfra
      ###################################################
      - name: Terraform Init (preinfra)
        run: terraform init
        working-directory: terraform-skillnest/terraform-preinfra

      - name: Terraform Plan (preinfra)
        run: terraform plan -input=false -lock-timeout=60s -out=tfplan.binary \
          -var="artifacts_bucket_name=arka-dev-artifacts" \
          -var="environment=dev" \
          -var="project=arka"
        working-directory: terraform-skillnest/terraform-preinfra

      - name: Terraform Apply (preinfra)
        run: terraform apply -input=false -auto-approve tfplan.binary
        working-directory: terraform-skillnest/terraform-preinfra

      ###################################################
      # MODULE 2: terraform-db
      ###################################################
      - name: Terraform Init (db)
        run: terraform init
        working-directory: terraform-skillnest/terraform-db

      - name: Terraform Plan (db)
        run: terraform plan -input=false -lock-timeout=60s -out=tfplan.binary \
          -var="environment=dev" \
          -var="project=arka"
        working-directory: terraform-skillnest/terraform-db

      - name: Terraform Apply (db)
        run: terraform apply -input=false -auto-approve tfplan.binary
        working-directory: terraform-skillnest/terraform-db

      ###################################################
      # MODULE 3: terraform-api-ecs
      ###################################################
      - name: Terraform Init (api-ecs)
        run: terraform init
        working-directory: terraform-skillnest/terraform-api-ecs

      - name: Terraform Plan (api-ecs)
        run: terraform plan -input=false -lock-timeout=60s -out=tfplan.binary \
          -var="environment=dev" \
          -var="project=arka"
        working-directory: terraform-skillnest/terraform-api-ecs

      - name: Terraform Apply (api-ecs)
        run: terraform apply -input=false -auto-approve tfplan.binary
        working-directory: terraform-skillnest/terraform-api-ecs
