name: terraform-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-skillnest/terraform-preinfra

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform-skillnest/terraform-preinfra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform-skillnest/terraform-preinfra
