name: terraform-deploy-all

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      ###################################################
      # MODULE 1: terraform-preinfra
      ###################################################
      - name: Terraform Init (preinfra)
        run: terraform -chdir=terraform-skillnest/terraform-preinfra init

      - name: Terraform Workspace Select (preinfra)
        run: terraform -chdir=terraform-skillnest/terraform-preinfra workspace select dev || terraform -chdir=terraform-skillnest/terraform-preinfra workspace new dev

      - name: Terraform Plan (preinfra)
        run: |
          terraform -chdir=terraform-skillnest/terraform-preinfra plan -input=false -lock-timeout=60s -out=tfplan.binary \
            -var="artifacts_bucket_name=arka-dev-artifacts" \
            -var="environment=dev" \
            -var="project=arka"

      - name: Terraform Apply (preinfra)
        run: terraform -chdir=terraform-skillnest/terraform-preinfra apply -input=false -auto-approve tfplan.binary

      ###################################################
      # MODULE 2: terraform-db
      ###################################################
      - name: Terraform Init (db)
        run: terraform -chdir=terraform-skillnest/terraform-db init

      - name: Terraform Workspace Select (db)
        run: terraform -chdir=terraform-skillnest/terraform-db workspace select dev || terraform -chdir=terraform-skillnest/terraform-db workspace new dev

      - name: Terraform Plan (db)
        run: |
          terraform -chdir=terraform-skillnest/terraform-db plan -input=false -lock-timeout=60s -out=tfplan.binary \
            -var="environment=dev" \
            -var="project=arka" \
            -var="db_identifier=arka-dev-db" \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="db_name=arkadb" \
            -var='vpc_id=vpc-0513a9bab7a11e39e' \
            -var='subnet_ids=["subnet-07a322f484b9f962","subnet-09ee219f4838cb06f"]'

      - name: Terraform Apply (db)
        run: terraform -chdir=terraform-skillnest/terraform-db apply -input=false -auto-approve tfplan.binary

      ###################################################
      # MODULE 3: terraform-api-ecs
      ###################################################
      - name: Terraform Init (api-ecs)
        run: terraform -chdir=terraform-skillnest/terraform-api-ecs init

      - name: Terraform Workspace Select (api-ecs)
        run: terraform -chdir=terraform-skillnest/terraform-api-ecs workspace select dev || terraform -chdir=terraform-skillnest/terraform-api-ecs workspace new dev

      - name: Terraform Plan (api-ecs)
        run: |
          terraform -chdir=terraform-skillnest/terraform-api-ecs plan -input=false -lock-timeout=60s -out=tfplan.binary \
            -var="environment=dev" \
            -var="project=arka" \
            -var="db_r2dbc_url=${{ secrets.DB_R2DBC_URL }}" \
            -var="db_jdbc_url=${{ secrets.DB_JDBC_URL }}" \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}"

      - name: Terraform Apply (api-ecs)
        run: terraform -chdir=terraform-skillnest/terraform-api-ecs apply -input=false -auto-approve tfplan.binary
