name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_db_r2dbc_url: ${{ secrets.DB_R2DBC_URL }}
      TF_VAR_db_jdbc_url: ${{ secrets.DB_JDBC_URL }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init & Apply - Preinfra
        working-directory: terraform-preinfra
        run: |
          terraform init -input=false
          terraform apply -auto-approve

      - name: Terraform Init & Apply - DB
        working-directory: terraform-db
        run: |
          terraform init -input=false
          terraform apply -auto-approve

      - name: Terraform Init & Apply - ECS
        working-directory: terraform-api-ecs
        run: |
          terraform init -input=false
          terraform apply -auto-approve
